### PR TITLE
Add zaptech/cookie-consent

### PR DESCRIPTION
**Pull request by robbot006**
## [zaptech/cookie-consent  at Packagist](https://packagist.org/packages/reflar/cookie-consent)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/zaptech/cookie-consent/stats)
## [ReFlar/cookie-consent at GitHub](https://github.com/ReFlar/cookie-consent)

GitHub license

[GitHub last tag](https://github.com/ReFlar/cookie-consent/releases) [GitHub contributors](https://github.com/ReFlar/cookie-consent/graphs/contributors)
[GitHub stars](https://github.com/ReFlar/cookie-consent/stargazers) [GitHub forks](https://github.com/ReFlar/cookie-consent/network) [GitHub issues](https://github.com/ReFlar/cookie-consent/issues)

[GitHub last commit](https://github.com/ReFlar/cookie-consent/commits) [GitHub commit activity](https://github.com/ReFlar/cookie-consent/graphs/contributors) [GitHub commit activity](https://github.com/ReFlar/cookie-consent/graphs/contributors)
## Other

https://flagrow.io/extensions/reflar/cookie-consent

### CODE REVIEW

**Comment by rob006** [comment]
Extension migrated to `reflar/cookie-consent` (it probably should be marked as abandoned at Packagist).

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
