### PR TITLE
Add andre-pullinen/ads

### PR DESCRIPTION
**Pull request by robbot006**
## [andre-pullinen/ads at Packagist](https://packagist.org/packages/andre-pullinen/ads)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/andre-pullinen/ads/stats)

## [andre-pullinen/ads at GitHub](https://github.com/andre-pullinen/ads)

GitHub license

[GitHub last tag](https://github.com/andre-pullinen/ads/releases) [GitHub contributors](https://github.com/andre-pullinen/ads/graphs/contributors)
[GitHub stars](https://github.com/andre-pullinen/ads/stargazers) [GitHub forks](https://github.com/andre-pullinen/ads/network) [GitHub issues](https://github.com/andre-pullinen/ads/issues)

[GitHub last commit](https://github.com/andre-pullinen/ads/commits) [GitHub commit activity](https://github.com/andre-pullinen/ads/graphs/contributors) [GitHub commit activity](https://github.com/andre-pullinen/ads/graphs/contributors)

## Other

https://extiverse.com/extension/andre-pullinen/ads
https://discuss.flarum.org/d/4785

### CODE REVIEW

**Comment by rob006** [comment]
Private fork.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
It looks like it is quite popular.

**Pull request merged**
