### PR TITLE
Add `lawaxi/level-ranks`

### PR DESCRIPTION
**Pull request by robbot006**
## [`lawaxi/level-ranks` at Packagist](https://packagist.org/packages/lawaxi/level-ranks)

License

Latest Stable Version Latest Unstable Version Flarum compatibility status
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/lawaxi/level-ranks/stats)

## [`Lawaxi/level-rank` at GitHub](https://github.com/Lawaxi/level-rank)

GitHub license

[GitHub last tag](https://github.com/Lawaxi/level-rank/releases) [GitHub contributors](https://github.com/Lawaxi/level-rank/graphs/contributors)
[GitHub stars](https://github.com/Lawaxi/level-rank/stargazers) [GitHub forks](https://github.com/Lawaxi/level-rank/network) [GitHub issues](https://github.com/Lawaxi/level-rank/issues)

[GitHub last commit](https://github.com/Lawaxi/level-rank/commits) [GitHub commit activity](https://github.com/Lawaxi/level-rank/graphs/contributors) [GitHub commit activity](https://github.com/Lawaxi/level-rank/graphs/contributors)

## Other

https://extiverse.com/extension/lawaxi/level-ranks
https://discuss.flarum.org/d/27869

### CODE REVIEW

**Comment by rob006** [comment]
Private fork of https://github.com/imorland/level-ranks

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
