### PR TITLE
Cleanup outdated translations

### PR DESCRIPTION
**Pull request by rob006**
These are outdated translations, that should no longer be needed. When extension removes some translation strings, Weblate does not remove them completely - they disapear from GUI and you can't translate them, but existing translations are kept in JSON files and exported to language packs to keep BC. But from time to time these outdated strings should be cleaned up, and Flarum 1.0.0 release is a good time to do this.

### CODE REVIEW

**Comment by rob006** [comment]
@Littlegolden @MichaelBelgium @qiaeru @Hiobi @B3K4682 @justoverclockl @IamDarkle @tolgaaaltas Please take a look at this, as this will affect your language packs. Although this change should be safe, let me know if some of these translations should be kept.

___

In addition, here are lists of files in language packs that are not managed by Weblate. These are probably translations for outdated extensions or just files with incorrect name. It should be safe to remove them, since these extensions probably will not work with Flarum 1.0 anyway. Although double check what it is  before you remove them.


## https://github.com/FlarumES/lang-spanish:

 * `locale/es-ES-informal/flagrow-fonts.yml`
 * `locale/es-ES-informal/flarum-auth-facebook.yml`
 * `locale/es-ES-informal/flarum-auth-github.yml`
 * `locale/es-ES-informal/flarum-auth-twitter.yml`
 * `locale/es-ES-informal/flarum-profile-views.yml`


## https://github.com/justoverclockl/flarum-italian-ext:

 * `locale/askvortsov-flarum-checklist.yml`
 * `locale/askvortsov-flarum-discussion-templates.yml`
 * `locale/askvortsov-flarum-moderator-warnings.yml`
 * `locale/davwheat-custom-sidenav-link.yml`
 * `locale/fof-auth-discord.yml`
 * `locale/fof-merge-discussion.yml`
 * `locale/ianm-html-head.yml`
 * `locale/justoverclock-contactme.yml`
 * `locale/justoverclock-guest-engagement.yml`
 * `locale/nearata-no-self-likes.yml`
 * `locale/v17development-flarum-badges.yml`
 * `locale/v17development-flarum-blog.yml`


## https://github.com/FFans/lang-japanese:

 * `locale/clarkwinkelmann-colorful-borders.yml`
 * `locale/clarkwinkelmann-post-date.yml`
 * `locale/clarkwinkelmann-post-license.yml`
 * `locale/clarkwinkelmann-silent-mailchimp.yml`
 * `locale/dem13n.yml`
 * `locale/extiverse-bazaar.yml`
 * `locale/extum-material2.yml`
 * `locale/fajuu-contactbutton.yml`
 * `locale/fajuu-icons.yml`
 * `locale/flagrow-ads.yml`
 * `locale/flagrow-analytics.yml`
 * `locale/flagrow-fonts.yml`
 * `locale/flagrow-mason.yml`
 * `locale/flagrow-passport.yml`
 * `locale/flagrow-upload.yml`
 * `locale/flarum-auth-facebook.yml`
 * `locale/flarum-auth-github.yml`
 * `locale/flarum-auth-twitter.yml`
 * `locale/flarumite-decontaminator.yml`
 * `locale/fof-auth-discord.yml`
 * `locale/fof-auth-gitlab.yml`
 * `locale/fof-email-checker.yml`
 * `locale/hiqstd-close.yml`
 * `locale/kilowhat-affiliation-links.yml`
 * `locale/kilowhat-mailing.yml`
 * `locale/kvothe-signup-button.yml`
 * `locale/manelizzard-notify.yml`
 * `locale/matpompili-imgur-upload.yml`
 * `locale/michaelBelgium-profile-views.yml`
 * `locale/migratetoflarum-vbulletin-redirects.yml`
 * `locale/minr-auth-qq.yml`
 * `locale/minr-auth-weibo.yml`
 * `locale/nikovonlas-web-push.yml`
 * `locale/nomiscz-auth-linkedin.yml`
 * `locale/reflar-cookie-consent.yml`
 * `locale/reflar-doorman.yml`
 * `locale/reflar-twofactor.yml`
 * `locale/reflar-webhooks.yml`
 * `locale/studosi-mail-filter.yml`
 * `locale/the-turk-diff.yml`
 * `locale/the-turk-edit-notifications.yml`
 * `locale/the-turk-extended-appearance.yml`
 * `locale/the-turk-mathren.yml`
 * `locale/the-turk-password-strength.yml`
 * `locale/the-turk-quiet-edits.yml`
 * `locale/veroz1-users-list.yml`
 * `locale/xmugenx-post-blacklist.yml`
 * `locale/zerosonesfun-announce.yml`
 * `locale/ziymed-backtowebsite.yml`


## https://github.com/B3K4682/lang-georgian:

 * `locale/artuu-imager.yml`
 * `locale/clarkwinkelmann-colorful-borders.yml`


## https://github.com/MichaelBelgium/flarum-dutch:

 * `locale/flarum-auth-facebook.yml`
 * `locale/flarum-auth-github.yml`
 * `locale/flarum-auth-twitter.yml`
 * `locale/saleskin-flarum-auth-google.yml`


## https://github.com/tolgaaaltas/flarum-lang-turkish:

 * `locale/flarum-auth-facebook.yml`
 * `locale/flarum-auth-github.yml`
 * `locale/flarum-auth-twitter.yml`


## https://github.com/tolgaaaltas/flarum-ext-turkish:

 * `locale/ michaelbelgium-flarum-profile-views.yml`
 * `locale/artuu-imager.yml`
 * `locale/askvortsov-copy-links.yml`
 * `locale/clarkWinkelmann-post-license.yml`
 * `locale/clarkwinkelmann-colorful-borders.yml`
 * `locale/clarkwinkelmann-post-date.yml`
 * `locale/clarkwinkelmann-silent-mailchimp.yml`
 * `locale/dem13n-auth-mailru.yml`
 * `locale/dem13n-auth-odnoklassniki.yml`
 * `locale/dem13n-auth-ok.yml`
 * `locale/dem13n-auth-vkontakte.yml`
 * `locale/dem13n-auth-yandex.yml`
 * `locale/dem13n-nickname-changer.yml`
 * `locale/dem13n-quad-theme.yml`
 * `locale/dexif-telegram.yml`
 * `locale/dotronglong-hide-me.yml`
 * `locale/estevao-simoes-microsoft-auth.yml`
 * `locale/extiverse-bazaar.yml`
 * `locale/extum-flarum-ext-material2.yml`
 * `locale/fajuu-contactbutton.yml`
 * `locale/fajuu-icons.yml`
 * `locale/flagrow-ads.yml`
 * `locale/flagrow-fonts.yml`
 * `locale/flagrow-telegram.yml`
 * `locale/flarum-calendar.yml`
 * `locale/flarum-microsoft-auth.yml`
 * `locale/fof-ads.yml`
 * `locale/fof-auth-discord.yml`
 * `locale/fof-auth-gitlab.yml`
 * `locale/fof-email-checker.yml`
 * `locale/fof-footer.yml`
 * `locale/fof-mailbox.yml`
 * `locale/fof-userbio.yml`
 * `locale/fof.geoip.yml`
 * `locale/funkeye-custom-welcome-hero.yml`
 * `locale/giga300-auth-discord.yml`
 * `locale/hiqstd-close.yml`
 * `locale/irony-bing-wallpaper.yml`
 * `locale/irony-code-insert.yml`
 * `locale/irony-google-search.yml`
 * `locale/irony-webhook.yml`
 * `locale/jasper-chevereto.yml`
 * `locale/kilowhat-affiliation-links.yml`
 * `locale/kilowhat-audit.yml`
 * `locale/kilowhat-mailing.yml`
 * `locale/kvothe-keyboard-shortcuts.yml`
 * `locale/kvothe-online-users.yml`
 * `locale/kvothe-signup-button.yml`
 * `locale/kvothe-spoiler-bbcode.yml`
 * `locale/kvothe-sub.yml`
 * `locale/kyrne-sylloge.yml`
 * `locale/migratetoflarum-itemlist-order.yml`
 * `locale/migratetoflarum-vbulletin-redirects.yml`
 * `locale/nearata-flarum-ext-minecraft-avatars.yml`
 * `locale/nearata-is-online.yml`
 * `locale/nearata-no-self-likes.yml`
 * `locale/nikovonlas-web-push.yml`
 * `locale/nikovonlas-webpush.yml`
 * `locale/nomiscz-auth-linkedin.yml`
 * `locale/oaklinq-reply2see.yml`
 * `locale/reflar-cookie-consent.yml`
 * `locale/reflar-doorman.yml`
 * `locale/squeevee-flarum-ext-fancybox.yml`
 * `locale/therealsujitk-flarum-ext-show-password.yml`
 * `locale/v17development-flarum-seo.yml`
 * `locale/veriael-markdown.yml`
 * `locale/vestosers-close.yml`
 * `locale/wiseclock-login2see.yml`
 * `locale/wiwatsrt-best-answer.yml`
 * `locale/wvbforum-post-license.yml`
 * `locale/xelson-pushedx-chat.yml`
 * `locale/xmugenx-post-blacklist.yml`
 * `locale/zerosonesfun-announce.yml`
 * `locale/zhishiq-pusher.yml`
 * `locale/zhishiq-redis.yml`
 * `locale/zhujia18-chevereto.yml`
 * `locale/ziymed-backtowebsite.yml`


## https://github.com/FFans/lang-simplified-chinese:

 * `locale/artuu-imager.yml`
 * `locale/askvortsov-copy-links.yml`
 * `locale/clarkwinkelmann-colorful-borders.yml`
 * `locale/clarkwinkelmann-post-date.yml`
 * `locale/clarkwinkelmann-post-license.yml`
 * `locale/clarkwinkelmann-silent-mailchimp.yml`
 * `locale/dem13n-auth-mailru.yml`
 * `locale/dem13n-auth-odnoklassniki.yml`
 * `locale/dem13n-auth-vkontakte.yml`
 * `locale/dem13n-auth-yandex.yml`
 * `locale/dem13n-nickname-changer.yml`
 * `locale/dem13n-quad-theme.yml`
 * `locale/dem13n.yml`
 * `locale/dexif-telegram.yml`
 * `locale/dotronglong-hide-me.yml`
 * `locale/estevao-simoes-microsoft-auth.yml`
 * `locale/extiverse-bazaar.yml`
 * `locale/extum-material2.yml`
 * `locale/fajuu-contactbutton.yml`
 * `locale/fajuu-icons.yml`
 * `locale/flagrow-ads.yml`
 * `locale/flagrow-analytics.yml`
 * `locale/flagrow-fonts.yml`
 * `locale/flagrow-mason.yml`
 * `locale/flagrow-passport.yml`
 * `locale/flagrow-upload.yml`
 * `locale/flarum-auth-facebook.yml`
 * `locale/flarum-auth-github.yml`
 * `locale/flarum-auth-twitter.yml`
 * `locale/flarumite-decontaminator.yml`
 * `locale/fof-auth-discord.yml`
 * `locale/fof-auth-gitlab.yml`
 * `locale/fof-email-checker.yml`
 * `locale/funkeye-custom-welcome-hero.yml`
 * `locale/giga300-auth-discord.yml`
 * `locale/hiqstd-close.yml`
 * `locale/irony-bing-wallpaper.yml`
 * `locale/irony-code-insert.yml`
 * `locale/irony-google-search.yml`
 * `locale/irony-webhook.yml`
 * `locale/kilowhat-affiliation-links.yml`
 * `locale/kilowhat-mailing.yml`
 * `locale/kvothe-keyboard-shortcuts.yml`
 * `locale/kvothe-online-users.yml`
 * `locale/kvothe-signup-button.yml`
 * `locale/kvothe-spoiler-bbcode.yml`
 * `locale/manelizzard-notify.yml`
 * `locale/matpompili-imgur-upload.yml`
 * `locale/migratetoflarum-itemlist-order.yml`
 * `locale/migratetoflarum-vbulletin-redirects.yml`
 * `locale/minr-auth-qq.yml`
 * `locale/minr-auth-weibo.yml`
 * `locale/nearata-is-online.yml`
 * `locale/nikovonlas-auth-vk.yml`
 * `locale/nikovonlas-web-push.yml`
 * `locale/nomiscz-auth-linkedin.yml`
 * `locale/reflar-cookie-consent.yml`
 * `locale/reflar-doorman.yml`
 * `locale/reflar-twofactor.yml`
 * `locale/reflar-webhooks.yml`
 * `locale/studosi-mail-filter.yml`
 * `locale/the-turk-diff.yml`
 * `locale/the-turk-edit-notifications.yml`
 * `locale/the-turk-extended-appearance.yml`
 * `locale/the-turk-mathren.yml`
 * `locale/the-turk-password-strength.yml`
 * `locale/the-turk-quiet-edits.yml`
 * `locale/the-turk-regrole.yml`
 * `locale/the-turk-welcome-widgets.yml`
 * `locale/veriael-markdown.yml`
 * `locale/veroz1-users-list.yml`
 * `locale/wiwatsrt-best-answer.yml`
 * `locale/wvbforum-post-license.yml`
 * `locale/xmugenx-post-blacklist.yml`
 * `locale/zerosonesfun-announce.yml`
 * `locale/zhishiq-pusher.yml`
 * `locale/zhishiq-queue.yml`
 * `locale/zhishiq-redis.yml`
 * `locale/zhujia18-chevereto.yml`
 * `locale/ziymed-backtowebsite.yml`

**Comment by IamDarkle** [comment]
All good, no problem with those translations. Thank you!

**Comment by qiaeru** [comment]
I see no issues with that, thank you!

**Comment by Hiobi** [comment]
It seems to be ok ! Thank @rob006 :)

**Pull request merged**
