### PR TITLE
Add jjwind320/flarum-ext-formatting

### PR DESCRIPTION
**Pull request by robbot006**
## [jjwind320/flarum-ext-formatting at Packagist](https://packagist.org/packages/jjwind320/flarum-ext-formatting)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/jjwind320/flarum-ext-formatting/stats)

## [jjwind320/flarum-ext-formatting at GitHub](https://github.com/jjwind320/flarum-ext-formatting)

GitHub license

[GitHub last tag](https://github.com/jjwind320/flarum-ext-formatting/releases) [GitHub contributors](https://github.com/jjwind320/flarum-ext-formatting/graphs/contributors)
[GitHub stars](https://github.com/jjwind320/flarum-ext-formatting/stargazers) [GitHub forks](https://github.com/jjwind320/flarum-ext-formatting/network) [GitHub issues](https://github.com/jjwind320/flarum-ext-formatting/issues)

[GitHub last commit](https://github.com/jjwind320/flarum-ext-formatting/commits) [GitHub commit activity](https://github.com/jjwind320/flarum-ext-formatting/graphs/contributors) [GitHub commit activity](https://github.com/jjwind320/flarum-ext-formatting/graphs/contributors)

## Other

https://flagrow.io/extensions/jjwind320/flarum-ext-formatting

### CODE REVIEW

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
Related: https://github.com/rob006-software/flarum-translations/pull/258

Closing for now since this seems to be some personal project/test.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
