### PR TITLE
Add `katosdev/signature`

### PR DESCRIPTION
**Pull request by robbot006**
## [`katosdev/signature` at Packagist](https://packagist.org/packages/katosdev/signature)

License

Latest Stable Version Latest Unstable Version Flarum compatibility status
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/katosdev/signature/stats)

## [`katosdev/signature` at GitHub](https://github.com/katosdev/signature)

GitHub license

[GitHub last tag](https://github.com/katosdev/signature/releases) [GitHub contributors](https://github.com/katosdev/signature/graphs/contributors)
[GitHub stars](https://github.com/katosdev/signature/stargazers) [GitHub forks](https://github.com/katosdev/signature/network) [GitHub issues](https://github.com/katosdev/signature/issues)

[GitHub last commit](https://github.com/katosdev/signature/commits) [GitHub commit activity](https://github.com/katosdev/signature/graphs/contributors) [GitHub commit activity](https://github.com/katosdev/signature/graphs/contributors)

## Other

https://extiverse.com/extension/katosdev/signature
https://discuss.flarum.org/d/28108-flarum-signature

### CODE REVIEW

**Comment by rob006** [comment]
@katosdev What is the status of Polish and Turkish translations bundled in your extension? I'm trying to exclude from Weblate languages that are already bundled in extensions - if translation for given language is already bundled with extension, there is no sense to have it duplicated in Weblate. But this is true only for actively maintained translations, which usually means only translations maintained by extension author. For example if extension author knows Italian, he can provide `en` and `it` translations, while the rest should probably be handled inside of respective language packs. So if you're not able to maintain Polish and Turkish translations on your own, it is probably better to remove them from repository and handle them by language packs and Weblate.

**Comment by tolgaaaltas** [comment]
@rob006 No problem for me, it's always easier to manage translations through Weblate. I just wanted to update it because it is in Turkish in the package. It's Katos' decision.

**Comment by katosdev** [comment]
The translations are not actively maintained and were pulled across from the previous extension that I updated.
Happy for these to be moved under weblate

**Comment by rob006** [comment]
I added this extension to Weblate, including Polish and Turkish. @katosdev I think that in that case translations could be removed from extension repository.

**Comment by katosdev** [comment]
> I added this extension to Weblate, including Polish and Turkish. @katosdev I think that in that case translations could be removed from extension repository.

Makes sense to me - Will do this in an upcoming update. Thanks @rob006

**Pull request merged**
