### PR TITLE
Add instkffff/user-bio-eveonline

### PR DESCRIPTION
**Pull request by robbot006**
## [instkffff/user-bio-eveonline at Packagist](https://packagist.org/packages/instkffff/user-bio-eveonline)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/instkffff/user-bio-eveonline/stats)

## [instkffff/user-bio-eveonline at GitHub](https://github.com/instkffff/user-bio-eveonline)

GitHub license

[GitHub last tag](https://github.com/instkffff/user-bio-eveonline/releases) [GitHub contributors](https://github.com/instkffff/user-bio-eveonline/graphs/contributors)
[GitHub stars](https://github.com/instkffff/user-bio-eveonline/stargazers) [GitHub forks](https://github.com/instkffff/user-bio-eveonline/network) [GitHub issues](https://github.com/instkffff/user-bio-eveonline/issues)

[GitHub last commit](https://github.com/instkffff/user-bio-eveonline/commits) [GitHub commit activity](https://github.com/instkffff/user-bio-eveonline/graphs/contributors) [GitHub commit activity](https://github.com/instkffff/user-bio-eveonline/graphs/contributors)

## Other

https://flagrow.io/extensions/instkffff/user-bio-eveonline

### CODE REVIEW

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
Fork without changed translations keys.

**Comment by rob006** [comment]
Stable release still points to `fof/user-bio` (https://github.com/instkffff/user-bio-eveonline/blob/0.1.2/composer.json) and master branch does not have translations at all.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
