### PR TITLE
Add soulteary/flarum-upload

### PR DESCRIPTION
**Pull request by robbot006**
## [soulteary/flarum-upload at Packagist](https://packagist.org/packages/soulteary/flarum-upload)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/soulteary/flarum-upload/stats)

## [soulteary/upload at GitHub](https://github.com/soulteary/upload)

GitHub license

[GitHub last tag](https://github.com/soulteary/upload/releases) [GitHub contributors](https://github.com/soulteary/upload/graphs/contributors)
[GitHub stars](https://github.com/soulteary/upload/stargazers) [GitHub forks](https://github.com/soulteary/upload/network) [GitHub issues](https://github.com/soulteary/upload/issues)

[GitHub last commit](https://github.com/soulteary/upload/commits) [GitHub commit activity](https://github.com/soulteary/upload/graphs/contributors) [GitHub commit activity](https://github.com/soulteary/upload/graphs/contributors)

## Other

https://flagrow.io/extensions/soulteary/flarum-upload
https://discuss.flarum.org/d/4154

### CODE REVIEW

**Comment by rob006** [comment]
Another fork without changed keys for translations.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
Closing - it has hardcoded Chinese strings, so it doesn't seems to care about translations. Also, it is no longer actively maintained.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
