### PR TITLE
Add `tohsakarat/table-of-content`

### PR DESCRIPTION
**Pull request by robbot006**
## [`tohsakarat/table-of-content` at Packagist](https://packagist.org/packages/tohsakarat/table-of-content)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/tohsakarat/table-of-content/stats)

## [`tohsakrat/flarum-table-of-content` at GitHub](https://github.com/tohsakrat/flarum-table-of-content)

GitHub license

[GitHub last tag](https://github.com/tohsakrat/flarum-table-of-content/releases) [GitHub contributors](https://github.com/tohsakrat/flarum-table-of-content/graphs/contributors)
[GitHub stars](https://github.com/tohsakrat/flarum-table-of-content/stargazers) [GitHub forks](https://github.com/tohsakrat/flarum-table-of-content/network) [GitHub issues](https://github.com/tohsakrat/flarum-table-of-content/issues)

[GitHub last commit](https://github.com/tohsakrat/flarum-table-of-content/commits) [GitHub commit activity](https://github.com/tohsakrat/flarum-table-of-content/graphs/contributors) [GitHub commit activity](https://github.com/tohsakrat/flarum-table-of-content/graphs/contributors)

## Other

https://extiverse.com/extension/tohsakarat/table-of-content
https://discuss.flarum.org/d/31409-table-of-content

### CODE REVIEW

**Comment by rob006** [comment]
It has translation files, but they're not used anywhere:

https://github.com/tohsakrat/flarum-table-of-content/blob/main/extend.php
https://github.com/search?q=repo%3Atohsakrat%2Fflarum-table-of-content+trans&type=code

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
> It has translation files, but they're not used anywhere:
> 
> https://github.com/tohsakrat/flarum-table-of-content/blob/main/extend.php https://github.com/search?q=repo%3Atohsakrat%2Fflarum-table-of-content+trans&type=code

This has been fixed in https://github.com/tohsakrat/flarum-table-of-content/commit/0a8c45b8e79790a98036a92257fcff2ce3985551#diff-7a2e9358ed6a0532c2127a4b11267e2a59d1747798cca77a26b140d61c31413c

**Comment by rob006** [comment]
> > It has translation files, but they're not used anywhere:
> > https://github.com/tohsakrat/flarum-table-of-content/blob/main/extend.php https://github.com/search?q=repo%3Atohsakrat%2Fflarum-table-of-content+trans&type=code
> 
> This has been fixed in [tohsakrat/flarum-table-of-content@0a8c45b#diff-7a2e9358ed6a0532c2127a4b11267e2a59d1747798cca77a26b140d61c31413c](https://github.com/tohsakrat/flarum-table-of-content/commit/0a8c45b8e79790a98036a92257fcff2ce3985551#diff-7a2e9358ed6a0532c2127a4b11267e2a59d1747798cca77a26b140d61c31413c)

Or not... This phrase still doesn't seem to be used anywhere: https://github.com/search?q=repo%3Atohsakrat%2Fflarum-table-of-content%20copied&type=code

**Comment by rob006** [comment]
https://discuss.flarum.org/d/31409-table-of-content/25

**Pull request merged**
