### PR TITLE
Add haunguyen/level-ranks

### PR DESCRIPTION
**Pull request by robbot006**
## [haunguyen/level-ranks at Packagist](https://packagist.org/packages/haunguyen/level-ranks)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/haunguyen/level-ranks/stats)

## [FLHauNguyen/level at GitHub](https://github.com/FLHauNguyen/level)

GitHub license

[GitHub last tag](https://github.com/FLHauNguyen/level/releases) [GitHub contributors](https://github.com/FLHauNguyen/level/graphs/contributors)
[GitHub stars](https://github.com/FLHauNguyen/level/stargazers) [GitHub forks](https://github.com/FLHauNguyen/level/network) [GitHub issues](https://github.com/FLHauNguyen/level/issues)

[GitHub last commit](https://github.com/FLHauNguyen/level/commits) [GitHub commit activity](https://github.com/FLHauNguyen/level/graphs/contributors) [GitHub commit activity](https://github.com/FLHauNguyen/level/graphs/contributors)

## Other

https://flagrow.io/extensions/haunguyen/level-ranks

### CODE REVIEW

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
Looks like private fork of https://github.com/ReFlar/level-ranks

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
