### PR TITLE
Add Vietnamese language

### PR DESCRIPTION
**Pull request by xuandung38**
Please check and merge it

### CODE REVIEW

**Comment by rob006** [comment]
There need to be integrated language pack to make use of these translations. Do you want to maintain such language pack? Or integrate it with https://github.com/datlechin/lang-vietnamese (@datlechin would need to confirm this).

See https://github.com/rob006-software/flarum-translations/wiki/How-to-start

**Comment by xuandung38** [comment]
It's no longer support sir

**Comment by rob006** [comment]
Weblate itself does not provide translations for Flarum, it can only export translations to language pack repository, so we need language pack and maintainer anyway. If you want to maintain such language pack, open an issue at https://github.com/flarum-lang/about, guys will help you with that. In other case we need to wait for volunteer which step up as maintainer (or wait for @datlechin maybe he will be interested).

**Comment by rob006** [comment]
I'm closing this since [existing Vietnamese language pack](https://discuss.flarum.org/d/22902-vietnamese-extention-for-flarum/11) is actively maintained again. 

If @datlechin will decide to integrate his language pack with Weblate, I will open another PR that mentions original source of translations.

**Pull request closed without merging**
