### PR TITLE
Add webbinaro/flarum-calendar

### PR DESCRIPTION
**Pull request by robbot006**
## [webbinaro/flarum-calendar at Packagist](https://packagist.org/packages/webbinaro/flarum-calendar)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/webbinaro/flarum-calendar/stats)

## [eddiewebb/flarum-calendar at GitHub](https://github.com/eddiewebb/flarum-calendar)

GitHub license

[GitHub last tag](https://github.com/eddiewebb/flarum-calendar/releases) [GitHub contributors](https://github.com/eddiewebb/flarum-calendar/graphs/contributors)
[GitHub stars](https://github.com/eddiewebb/flarum-calendar/stargazers) [GitHub forks](https://github.com/eddiewebb/flarum-calendar/network) [GitHub issues](https://github.com/eddiewebb/flarum-calendar/issues)

[GitHub last commit](https://github.com/eddiewebb/flarum-calendar/commits) [GitHub commit activity](https://github.com/eddiewebb/flarum-calendar/graphs/contributors) [GitHub commit activity](https://github.com/eddiewebb/flarum-calendar/graphs/contributors)

## Other

https://extiverse.com/extension/webbinaro/flarum-calendar
https://discuss.flarum.org/d/24429-events-calendar-wip-help-wanted

### CODE REVIEW

**Comment by rob006** [comment]
It is WIP: https://discuss.flarum.org/d/24429-events-calendar-wip-help-wanted

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request merged**
