### PR TITLE
Add `flamarkt/backoffice`

### PR DESCRIPTION
**Pull request by robbot006**
## [`flamarkt/backoffice` at Packagist](https://packagist.org/packages/flamarkt/backoffice)

License

Latest Stable Version Latest Unstable Version Flarum compatibility status
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/flamarkt/backoffice/stats)

## [`flamarkt/backoffice` at GitHub](https://github.com/flamarkt/backoffice)

GitHub license

[GitHub last tag](https://github.com/flamarkt/backoffice/releases) [GitHub contributors](https://github.com/flamarkt/backoffice/graphs/contributors)
[GitHub stars](https://github.com/flamarkt/backoffice/stargazers) [GitHub forks](https://github.com/flamarkt/backoffice/network) [GitHub issues](https://github.com/flamarkt/backoffice/issues)

[GitHub last commit](https://github.com/flamarkt/backoffice/commits) [GitHub commit activity](https://github.com/flamarkt/backoffice/graphs/contributors) [GitHub commit activity](https://github.com/flamarkt/backoffice/graphs/contributors)

## Other

https://extiverse.com/extension/flamarkt/backoffice
https://discuss.flarum.org/d/30498-flamarkt-backoffice

### CODE REVIEW

**Comment by realodix** [comment]
@rob006 I think `flamarkt/core` is needed to complement `flamarkt/backoffice`

https://github.com/flamarkt/core/blob/main/resources/locale/en.yml

**Comment by rob006** [comment]
@realodix It does not have a release yet and I can't find any mention of it at https://discuss.flarum.org . How do you use this package?

/cc @clarkwinkelmann

**Comment by realodix** [comment]
Sorry, it seems because I have installed other flamarkt extensions such as 
- https://packagist.org/packages/flamarkt/order-tags
- https://packagist.org/packages/flamarkt/balance

**Comment by rob006** [comment]
They don't have releases either (and `flamarkt/balance` also have translations).

@clarkwinkelmann Do you have plans to tag releases for these extensions in near future?

**Comment by clarkwinkelmann** [comment]
`flamarkt/backoffice` has tagged releases and is an official package. The only other officially released packages under the namespace are `flamarkt/taxonomies` and `flamarkt/matomo`. Those are standalone extensions that can be outside outside of the Flamarkt ecosystem.

All the other `flamarkt/*` packages are unfinished extensions currently on perpetual hold.

`flamarkt/core` is not required by Backoffice, Taxonomies or Matomo. It's only required by the other unfinished extensions. It's not tagged either.

**Comment by rob006** [comment]
@realodix I'm not going to add unfinished extensions to Weblate, sorry. If you're using these, you can translate them on your own using this guide: https://rob006.net/en/blog/how-to-change-or-add-missing-translations-for-flarum/

**Pull request merged**
