### PR TITLE
Add v17development/flarum-blog

### PR DESCRIPTION
**Pull request by robbot006**
## [v17development/flarum-blog at Packagist](https://packagist.org/packages/v17development/flarum-blog)

License

Latest Stable Version Latest Unstable Version
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/v17development/flarum-blog/stats)

## [v17development/flarum-blog at GitHub](https://github.com/v17development/flarum-blog)

GitHub license

[GitHub last tag](https://github.com/v17development/flarum-blog/releases) [GitHub contributors](https://github.com/v17development/flarum-blog/graphs/contributors)
[GitHub stars](https://github.com/v17development/flarum-blog/stargazers) [GitHub forks](https://github.com/v17development/flarum-blog/network) [GitHub issues](https://github.com/v17development/flarum-blog/issues)

[GitHub last commit](https://github.com/v17development/flarum-blog/commits) [GitHub commit activity](https://github.com/v17development/flarum-blog/graphs/contributors) [GitHub commit activity](https://github.com/v17development/flarum-blog/graphs/contributors)

## Other

https://extiverse.com/extension/v17development/flarum-blog

### CODE REVIEW

**Comment by rob006** [comment]
This is beta 13 only, let's wait till beta 14 support will be added.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by rob006** [comment]
Adding, since it was requested by @tolgaaaltas: https://discuss.flarum.org/d/25392-blog-adds-a-blog-section-to-your-community/46

**Pull request merged**
