### PR TITLE
Add `lawaxi/harmony`

### PR DESCRIPTION
**Pull request by robbot006**
## [`lawaxi/harmony` at Packagist](https://packagist.org/packages/lawaxi/harmony)

License

Latest Stable Version Latest Unstable Version Flarum compatibility status
[Total Downloads Monthly Downloads Daily Downloads](https://packagist.org/packages/lawaxi/harmony/stats)

## [`Lawaxi/harmony` at GitHub](https://github.com/Lawaxi/harmony)

GitHub license

[GitHub last tag](https://github.com/Lawaxi/harmony/releases) [GitHub contributors](https://github.com/Lawaxi/harmony/graphs/contributors)
[GitHub stars](https://github.com/Lawaxi/harmony/stargazers) [GitHub forks](https://github.com/Lawaxi/harmony/network) [GitHub issues](https://github.com/Lawaxi/harmony/issues)

[GitHub last commit](https://github.com/Lawaxi/harmony/commits) [GitHub commit activity](https://github.com/Lawaxi/harmony/graphs/contributors) [GitHub commit activity](https://github.com/Lawaxi/harmony/graphs/contributors)

## Other

https://extiverse.com/extension/lawaxi/harmony
http://a.piece.of.shit/

### CODE REVIEW

**Comment by rob006** [comment]
Looks like garbage: https://github.com/Lawaxi/harmony/blob/e46e618a77854a04f0b966d313b222baab335643/composer.json#L19-L21

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Comment by robbot006** [comment]
Pull request updated.

**Pull request closed without merging**
